# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Commands and Apps to be executed at launch

exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = hyprsession
exec-once = ulauncher --hide-window
exec-once = slack
exec-once = 1password --silent
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Mint-Y-Dark-Pink'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
