# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds 

# /* ---- ✴️ Variables ✴️ ---- */  #
$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts
$UserConfigs = $HOME/.config/hypr/UserConfigs

bindd = CTRL, SPACE, Open ULauncher, exec, ulauncher-toggle

# Print = screenshot to clipboard only
bindd = , Print, Screenshot area to clipboard, exec, $HOME/.local/bin/screenshot.sh

# SHIFT + Print = record screen
bindd = SHIFT, PRINT, Toggle screen recording, exec, $HOME/.local/bin/record-screen.sh

# Unbind existing Super+Shift+S
unbind = SUPER SHIFT, S

# Lock screen
bindd = SUPER SHIFT, S, lock screen, exec, $UserScripts/LockScreenRandom.sh && hyprlock
bindd = SUPER, L, select lock screen wallpaper, exec, $UserScripts/LockScreenSelect.sh

# Wallpaper manager
unbind = SUPER, M
bindd = SUPER, M, wallpaper manager, exec, $UserScripts/WallpaperManager.sh

# Font manager
bindd = SUPER, F, font manager, exec, $UserScripts/FontManager.sh


#  IMPORTANT: If you want to remap and existing keybind you MUST unbindd it first 

# The bindings are CASE SENSITIVE. We suggest you copy the exisitng binding here
#  Then change `bindd` to `unbind`

# E.g. 
# unbind = $mainMod, Return, Open terminal, exec, $term
# bindd = $mainMod, Return, Open terminal, exec, ghostty 
#
# unbind = $mainMod, E, file manager, exec, $files
# bindd = $mainMod, T, file manager, exec, $files

# If you are ADDING a bindd, make sure you include the description 
# Other the keybind search menu might not show it properly 

# E.g.
# bindd = $mainMod, Z, My z app, exec APPNAME


# Switch workspaces on focused monitor
unbind = $mainMod, code:10
unbind = $mainMod, code:11
unbind = $mainMod, code:12
unbind = $mainMod, code:13
unbind = $mainMod, code:14
unbind = $mainMod, code:15
unbind = $mainMod, code:16
unbind = $mainMod, code:17
unbind = $mainMod, code:18
unbind = $mainMod, code:19

bindd = $mainMod, code:10, workspace 1 (focused monitor), focusworkspaceoncurrentmonitor, 1
bindd = $mainMod, code:11, workspace 2 (focused monitor), focusworkspaceoncurrentmonitor, 2
bindd = $mainMod, code:12, workspace 3 (focused monitor), focusworkspaceoncurrentmonitor, 3
bindd = $mainMod, code:13, workspace 4 (focused monitor), focusworkspaceoncurrentmonitor, 4
bindd = $mainMod, code:14, workspace 5 (focused monitor), focusworkspaceoncurrentmonitor, 5
bindd = $mainMod, code:15, workspace 6 (focused monitor), focusworkspaceoncurrentmonitor, 6
bindd = $mainMod, code:16, workspace 7 (focused monitor), focusworkspaceoncurrentmonitor, 7
bindd = $mainMod, code:17, workspace 8 (focused monitor), focusworkspaceoncurrentmonitor, 8
bindd = $mainMod, code:18, workspace 9 (focused monitor), focusworkspaceoncurrentmonitor, 9
bindd = $mainMod, code:19, workspace 10 (focused monitor), focusworkspaceoncurrentmonitor, 10






# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset
