# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #EDEAE6
background         #2A2C2D
cursor             #B5B6B2

active_tab_foreground     #2A2C2D
active_tab_background     #EDEAE6
inactive_tab_foreground   #EDEAE6
inactive_tab_background   #2A2C2D

active_border_color   #EDEAE6
inactive_border_color #2A2C2D
bell_border_color     #404846

color0      #4F5152
color1		#404846
color2		#5D625E
color3		#6F706B
color4		#817F78
color5		#85817B
color6		#999289
color7		#DDD9D3
color8		#9B9893
color9		#56605D
color10		#7C827E
color11		#94958F
color12		#ACA9A0
color13		#B1ACA3
color14		#CCC3B7
color15		#DDD9D3
