# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2C2D)
$foreground = rgb(EDEAE6)
$color0 = rgb(4F5152)
$color1 = rgb(404846)
$color2 = rgb(5D625E)
$color3 = rgb(6F706B)
$color4 = rgb(817F78)
$color5 = rgb(85817B)
$color6 = rgb(999289)
$color7 = rgb(DDD9D3)
$color8 = rgb(9B9893)
$color9 = rgb(56605D)
$color10 = rgb(7C827E)
$color11 = rgb(94958F)
$color12 = rgb(ACA9A0)
$color13 = rgb(B1ACA3)
$color14 = rgb(CCC3B7)
$color15 = rgb(DDD9D3)
